# Generated by Django 6.0.6 on 2026-06-08 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerequest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="properties.tenantprofile",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="properties.unit",
            ),
        ),
    ]
