# Generated by Django 6.0.6 on 2026-06-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
        ("properties", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="checkout_request_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "completed"])),
                fields=("lease", "month_paid"),
                name="unique_active_payment_per_month",
            ),
        ),
    ]
