# Generated by Django 6.0.6 on 2026-06-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_paymentreminder_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="pay_phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="paymentreminder",
            name="sms_sent",
            field=models.BooleanField(default=False),
        ),
    ]
