# Generated by Django 6.0.6 on 2026-06-14 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_payment_pay_phone_number_paymentreminder_sms_sent"),
        ("properties", "0002_initial"),
        ("users", "0004_activitylog_severity_organizationmpesaconfig_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("mpesa", "M-PESA"), ("cash", "Cash"), ("bank", "Bank")],
                default="mpesa",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="paymentreminder",
            name="whatsapp_link",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="CashCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("month_paid", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "receipt_photo",
                    models.FileField(blank=True, null=True, upload_to="cash_receipts/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Owner Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_collections",
                        to="properties.lease",
                    ),
                ),
                (
                    "linked_payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_collection",
                        to="payments.payment",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_collections_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_collections_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_bundle", models.JSONField()),
                ("pdf_path", models.CharField(blank=True, max_length=500)),
                ("sha256_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_snapshots",
                        to="properties.tenantprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MpesaStatementImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("matched_count", models.PositiveIntegerField(default=0)),
                ("orphan_count", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpesa_imports",
                        to="users.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="MpesaStatementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateTimeField(blank=True, null=True)),
                ("receipt_number", models.CharField(db_index=True, max_length=50)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("account_reference", models.CharField(blank=True, max_length=100)),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("orphan", "Orphan (unmatched)"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="orphan",
                        max_length=12,
                    ),
                ),
                ("raw_row", models.TextField(blank=True)),
                (
                    "matched_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="statement_lines",
                        to="payments.payment",
                    ),
                ),
                (
                    "statement_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payments.mpesastatementimport",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="UtilityCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "utility_type",
                    models.CharField(
                        choices=[
                            ("water", "Water"),
                            ("electricity", "Electricity"),
                            ("service", "Service Charge"),
                            ("garbage", "Garbage"),
                            ("other", "Other"),
                        ],
                        default="service",
                        max_length=15,
                    ),
                ),
                ("month", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_charges",
                        to="properties.lease",
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
                "unique_together": {("lease", "utility_type", "month")},
            },
        ),
    ]
