# Generated by Django 6.0.6 on 2026-06-22 15:17

import django.db.models.deletion
from django.db import migrations, models


def backfill_payment_allocations(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    for payment in Payment.objects.filter(status='completed'):
        payment.rent_applied = payment.amount
        payment.wallet_applied = 0
        payment.save(update_fields=['rent_applied', 'wallet_applied'])


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0006_payment_payment_method_paymentreminder_whatsapp_link_and_more",
        ),
        ("properties", "0004_tenantprofile_id_cards"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("rent_application", "Rent Application"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rent_month", models.DateField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="payment",
            name="unique_active_payment_per_month",
        ),
        migrations.AddField(
            model_name="payment",
            name="rent_applied",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="wallet_applied",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="tenantwallet",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to="properties.tenantprofile",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="lease",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transactions",
                to="properties.lease",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transactions",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="payments.tenantwallet",
            ),
        ),
        migrations.RunPython(backfill_payment_allocations, migrations.RunPython.noop),
    ]
