# Generated by Django 6.0.6 on 2026-06-14 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="severity",
            field=models.CharField(
                choices=[("info", "Info"), ("warning", "Warning"), ("high", "High")],
                default="info",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="OrganizationMpesaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("paybill", "Paybill"),
                            ("till", "Till Number"),
                            ("stk", "STK Push (platform)"),
                        ],
                        default="stk",
                        max_length=10,
                    ),
                ),
                (
                    "shortcode",
                    models.CharField(
                        blank=True, help_text="Paybill or Till number", max_length=20
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Paybill account reference prefix",
                        max_length=50,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpesa_config",
                        to="users.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnerAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("blocked_action", "Blocked Action"),
                            ("sensitive_access", "Sensitive Access"),
                            ("cash_pending", "Cash Pending Approval"),
                            ("reconciliation", "Reconciliation Issue"),
                            ("integrity", "Payment Integrity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("resource", models.CharField(blank=True, max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_alerts",
                        to="users.organization",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
