# Generated by Django 6.0.6 on 2026-06-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_activitylog_severity_organizationmpesaconfig_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="plan",
        ),
    ]
