# Generated by Django 6.0.6 on 2026-06-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_phone_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmpesaconfig",
            name="consumer_key_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organizationmpesaconfig",
            name="consumer_secret_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organizationmpesaconfig",
            name="mpesa_env",
            field=models.CharField(
                choices=[("sandbox", "Sandbox"), ("production", "Production")],
                default="sandbox",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="organizationmpesaconfig",
            name="passkey_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="organizationmpesaconfig",
            name="channel",
            field=models.CharField(
                choices=[
                    ("paybill", "Paybill"),
                    ("till", "Till Number"),
                    ("stk", "STK Push (your Paybill/Till)"),
                ],
                default="stk",
                max_length=10,
            ),
        ),
    ]
