# Generated by Django 6.0.6

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_password_reset_login_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaIntegrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending review'),
                        ('in_progress', 'In progress'),
                        ('completed', 'Completed'),
                        ('rejected', 'Rejected'),
                    ],
                    default='pending',
                    max_length=20,
                )),
                ('channel', models.CharField(
                    choices=[('till', 'Till Number'), ('paybill', 'Paybill')],
                    max_length=10,
                )),
                ('shortcode', models.CharField(help_text='Till or Paybill number', max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('mpesa_username', models.CharField(help_text='M-PESA portal username from Safaricom email', max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('account_number', models.CharField(blank=True, help_text='Paybill account number if applicable', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Extra details from Safaricom email')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for the Propizy team')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='mpesa_integration_requests',
                    to='users.organization',
                )),
                ('requested_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='mpesa_integration_requests',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('reviewed_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='reviewed_mpesa_requests',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
